---
- name: LogDNA Agent Package Public Key
  become: true
  become_method: sudo
  apt_key:
    url: https://assets.logdna.com/logdna.gpg

- name: LogDNA Agent Repository
  become: true
  become_method: sudo
  apt_repository:
    repo: deb https://assets.logdna.com stable main

- name: Install LogDNA Agent
  become: true
  become_method: sudo
  apt:
    state: latest
    name: logdna-agent
    update_cache: true
