---

- include_tasks: build.yml
  when: logdna_agent_install
  tags: [logdna]

- include_tasks: configure.yml
  when: logdna_agent_install
  tags: [logdna]

- include_tasks: service.yml
  when: logdna_agent_install
  tags: [logdna]
